repos:
-   repo: local
    hooks:
    -   id: nbconvert
        name: Tidy Jupyter Notebooks
        entry: pixi run python -m nbconvert --execute --inplace --ExecutePreprocessor.record_timing=False
        language: system
        files: \.ipynb$
        stages: [pre-commit]