[project]
authors = ["Austin Lee <Austin__Lee@outlook.com>"]
channels = ["conda-forge"]
description = "Numerik II Homework"
name = "Numerik II"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
jupyterlab = ">=4.3.1,<4.4"
numpy = ">=2.1.3,<2.2"
matplotlib = ">=3.9.2,<3.10"
