[project]
authors = ["Austin Lee <Austin__Lee@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Numerik II"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
jupyterlab = ">=4.3.1,<5"
numpy = ">=2.1.3,<3"
